aws_dbt_snowflake_project:
  outputs:
    dev:
      account: YRMGCNX-CR20557
      database: AIRBNB
      password: "Ankit@123456789"
      role: ACCOUNTADMIN
      schema: dbt_schema
      threads: 1
      type: snowflake
      user: ANKIT455
      warehouse: COMPUTE_WH
  target: dev
